### ISSUE TITLE
Add a endpoint to add songs or playlists to a party after a user joined it

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#14]

**Comment by Ekwav** [comment]
You should be able to add songs to a playlist with `POST /lists/{listId}/songs` 
Does that not work for you?

**Comment by Ekwav** [comment]
Upvoting a song in a party will add it if its not present (in case you want to add one to a party)  
I thought that makes more sense than requiring two requests since you probably want to upvote a song when you add it to an existing party or the adding should "cost" one upvote in case those get limited which they currently are not.
